apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Conestoga\Course2-DevOps\Sem2\ContainerOrchestration\FinalProject\final-assignment-crm\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: crm
  name: crm
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: crm
