- name: Deploy CRM to Kubernetes
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Deploy Helm chart to Kubernetes
      kubernetes.core.helm:
        name: crm-app
        chart_ref: ./crm-helm-chart
        release_namespace: default
        state: present
        wait: true

    - name: Wait for pods to be ready
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: default
        label_selectors:
          - app=crm
        wait: yes
        wait_timeout: 300


