apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\Conestoga\Course2-DevOps\Sem2\ContainerOrchestration\FinalProject\final-assignment-crm\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: adminer-container
  name: adminer-container
spec:
  ports:
    - name: "8078"
      port: 8078
      targetPort: 8080
  selector:
    io.kompose.service: adminer-container
