name: Build and Push Docker Image
run-name: ${{ gitea.actor }} is building Docker image
on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            submodules: true

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to Gitea Container Registry
          uses: docker/login-action@v3
          with:
            registry: gitea.devsecmindset.dev
            username: Nikhil
            password: ${{ secrets.GITEATOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: |
              gitea.devsecmindset.dev/nikhil/final-assignment-crm:latest
              gitea.devsecmindset.dev/nikhil/final-assignment-crm:${{ gitea.sha }}